cmake_minimum_required(VERSION 3.25)

project(hermes-3 LANGUAGES CXX C)

# Extra CMake scripts in cmake/ subdirectory
set(CMAKE_MODULE_PATH "${PROJECT_SOURCE_DIR}/cmake" ${CMAKE_MODULE_PATH})

option(HERMES_UPDATE_GIT_SUBMODULE
       "Check submodules are up-to-date during build" ON)
# Adapted from
# https://cliutils.gitlab.io/modern-cmake/chapters/projects/submodule.html
# Update submodules as needed
function(hermes_update_submodules)
  if(NOT HERMES_UPDATE_GIT_SUBMODULE)
    return()
  endif()
  find_package(Git QUIET)
  if(GIT_FOUND AND EXISTS "${PROJECT_SOURCE_DIR}/.git")
    message(STATUS "Submodule update")
    execute_process(
      COMMAND ${GIT_EXECUTABLE} -c submodule.recurse=false submodule update
              --init --recursive
      WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
      RESULT_VARIABLE GIT_SUBMOD_RESULT)
    if(NOT GIT_SUBMOD_RESULT EQUAL "0")
      message(
        FATAL_ERROR
          "git submodule update --init failed with ${GIT_SUBMOD_RESULT}, please checkout submodules"
      )
    endif()
  endif()
endfunction()
hermes_update_submodules()

# Get the Git revision
include(GetGitRevisionDescription)
get_git_head_revision(GIT_REFSPEC HERMES_REVISION)
if(HERMES_REVISION STREQUAL "GITDIR-NOTFOUND")
  set(HERMES_REVISION "Unknown")
endif()
message(STATUS "Git revision: ${HERMES_REVISION}")

# BOUT++ is a dependency
option(HERMES_BUILD_BOUT "Build BOUT++ in external/BOUT-dev" ON)
if(HERMES_BUILD_BOUT)
  set(BOUT_BUILD_EXAMPLES, OFF) # Don't create example makefiles
  set(HERMES_BOUT_SRC
      "external/BOUT-dev"
      CACHE STRING "Directory of BOUT++ dir")
  add_subdirectory(${HERMES_BOUT_SRC}
                   ${CMAKE_CURRENT_BINARY_DIR}/external/BOUT-dev SYSTEM)
else()
  find_package(bout++ REQUIRED)
endif()

include("./cmake/Sanitizers.cmake")

set(HERMES_SOURCES
    src/amjuel_data.cxx
    src/braginskii_collisions.cxx
    src/braginskii_conduction.cxx
    src/braginskii_electron_viscosity.cxx
    src/braginskii_friction.cxx
    src/braginskii_heat_exchange.cxx
    src/braginskii_thermal_force.cxx
    src/braginskii_ion_viscosity.cxx
    src/classical_diffusion.cxx
    src/component.cxx
    src/component_scheduler.cxx
    src/cx_reaction.cxx
    src/ionisation.cxx
    src/izn_rec_reaction.cxx
    src/div_ops.cxx
    src/neutral_mixed.cxx
    src/neutral_full_velocity.cxx
    src/electromagnetic.cxx
    src/electron_force_balance.cxx
    src/evolve_density.cxx
    src/evolve_energy.cxx
    src/evolve_pressure.cxx
    src/evolve_momentum.cxx
    src/external_apar.cxx
    src/guarded_options.cxx
    src/isothermal.cxx
    src/quasineutral.cxx
    src/diamagnetic_drift.cxx
    src/recalculate_metric.cxx
    src/relax_potential.cxx
    src/sheath_closure.cxx
    src/sheath_boundary.cxx
    src/sheath_boundary_fci.cxx
    src/sheath_boundary_simple.cxx
    src/sheath_boundary_insulating.cxx
    src/snb_conduction.cxx
    src/fixed_fraction_ions.cxx
    src/sound_speed.cxx
    src/zero_current.cxx
    src/anomalous_diffusion.cxx
    src/anomalous_diffusion_3d.cxx
    src/binormal_stpm.cxx
    src/recycling.cxx
    src/adas_reaction.cxx
    src/noflow_boundary.cxx
    src/neutral_parallel_diffusion.cxx
    src/neutral_boundary.cxx
    src/permissions.cxx
    src/polarisation_drift.cxx
    src/solkit_neutral_parallel_diffusion.cxx
    src/solkit_hydrogen_charge_exchange.cxx
    src/upstream_density_feedback.cxx
    src/temperature_feedback.cxx
    src/detachment_controller.cxx
    src/reaction.cxx
    src/reaction_data.cxx
    src/reaction_parser.cxx
    src/species_parser.cxx
    src/fieldline_geometry.cxx
    src/transform.cxx
    src/vorticity.cxx
    include/adas_reaction.hxx
    include/adas_carbon.hxx
    include/adas_neon.hxx
    include/amjuel_data.hxx
    include/anomalous_diffusion.hxx
    include/anomalous_diffusion_3d.hxx
    include/classical_diffusion.hxx
    include/cx_reaction.hxx
    include/binormal_stpm.hxx
    include/braginskii_collisions.hxx
    include/braginskii_conduction.hxx
    include/braginskii_electron_viscosity.hxx
    include/braginskii_friction.hxx
    include/braginskii_heat_exchange.hxx
    include/braginskii_ion_viscosity.hxx
    include/braginskii_thermal_force.hxx
    include/component.hxx
    include/component_scheduler.hxx
    include/diamagnetic_drift.hxx
    include/div_ops.hxx
    include/electromagnetic.hxx
    include/electron_force_balance.hxx
    include/evolve_density.hxx
    include/evolve_energy.hxx
    include/evolve_momentum.hxx
    include/evolve_pressure.hxx
    include/external_apar.hxx
    include/fixed_density.hxx
    include/fixed_fraction_ions.hxx
    include/fixed_velocity.hxx
    include/guarded_options.hxx
    include/neutral_full_velocity.hxx
    include/hermes_utils.hxx
    include/solkit_hydrogen_charge_exchange.hxx
    include/integrate.hxx
    include/ionisation.hxx
    include/izn_rec_reaction.hxx
    include/neutral_boundary.hxx
    include/neutral_mixed.hxx
    include/neutral_parallel_diffusion.hxx
    include/solkit_neutral_parallel_diffusion.hxx
    include/noflow_boundary.hxx
    include/permissions.hxx
    include/polarisation_drift.hxx
    include/quasineutral.hxx
    include/reaction.hxx
    include/reaction_data.hxx
    include/reaction_settings.hxx
    include/recalculate_metric.hxx
    include/recycling.hxx
    include/relax_potential.hxx
    include/sheath_boundary.hxx
    include/sheath_boundary_fci.hxx	
    include/sheath_boundary_simple.hxx
    include/sheath_boundary_insulating.hxx
    include/simple_conduction.hxx
    include/snb_conduction.hxx
    include/sheath_closure.hxx
    include/sound_speed.hxx
    include/species_parser.hxx
    include/upstream_density_feedback.hxx
    include/temperature_feedback.hxx
    include/detachment_controller.hxx
    include/vorticity.hxx
    include/zero_current.hxx
    include/transform.hxx
    include/fixed_fraction_radiation.hxx
    include/simple_pump.hxx
    include/fieldline_geometry.hxx)

# Compile Hermes sources into a library, which can be used for unit tests
add_library(hermes-3-lib ${HERMES_SOURCES})

target_link_libraries(hermes-3-lib PRIVATE bout++::bout++)

target_compile_features(hermes-3-lib PUBLIC cxx_std_17)
set_target_properties(hermes-3-lib PROPERTIES CXX_EXTENSIONS OFF)

target_include_directories(
  hermes-3-lib
  PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
         $<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}/include>
         $<INSTALL_INTERFACE:include>)

# Have hermes-3-lib look for dynamic libs in ./ before searching elsewhere
set_target_properties(hermes-3-lib PROPERTIES BUILD_RPATH "$ORIGIN")

enable_sanitizers(hermes-3-lib)

# The main executable target
add_executable(hermes-3 hermes-3.cxx
                        ${CMAKE_CURRENT_BINARY_DIR}/include/revision.hxx)

target_link_libraries(hermes-3 PRIVATE bout++::bout++ hermes-3-lib)

target_include_directories(
  hermes-3
  PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
         $<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}/include>
         $<INSTALL_INTERFACE:include>)

# Have hermes-3 look for dynamic libs in ./ before searching elsewhere
set_target_properties(hermes-3 PROPERTIES BUILD_RPATH "$ORIGIN")

option(HERMES_ENABLE_WARNINGS "Enable compiler warnings"
       ${PROJECT_IS_TOP_LEVEL})
option(HERMES_ERROR_ON_WARNINGS "Enable compiler warnings" OFF)
include(CompilerWarnings)
add_library(hermes_warnings INTERFACE)
hermes_set_project_warnings(hermes_warnings ${HERMES_ERROR_ON_WARNINGS} "" ""
                            "" "")

if(HERMES_ENABLE_WARNINGS)
  target_link_libraries(hermes-3-lib PRIVATE hermes_warnings)
  target_link_libraries(hermes-3 PRIVATE hermes_warnings)
endif()

# Build the file containing just the commit hash This will be rebuilt on every
# commit!
configure_file("${PROJECT_SOURCE_DIR}/include/revision.hxx.in"
               "${PROJECT_BINARY_DIR}/include/revision.hxx")

# Once built, copy the data and test directories
option(HERMES_COPY_EXAMPLES_TO_BUILD "Copy the examples to the build directory"
       ON)

option(HERMES_COPY_JSON_DATABASE_TO_BUILD
       "Copy the json database to the build directory" ON)

if(HERMES_COPY_EXAMPLES_TO_BUILD OR HERMES_COPY_JSON_DATABASE_TO_BUILD)
  add_custom_target(setup-examples ALL)
else()
  add_custom_target(setup-examples)
endif()

# Tests
option(HERMES_COPY_TESTS_TO_BUILD "Copy the tests to the build directory" ON)
option(HERMES_TESTS "Build the tests" ON)
if(HERMES_COPY_TESTS_TO_BUILD OR HERMES_TESTS)
  add_custom_target(setup-test ALL)
else()
  add_custom_target(setup-test)
endif()

# copy the data and test directories
if(EXISTS ${CMAKE_SOURCE_DIR}/examples)
  add_custom_command(
    TARGET setup-examples
    PRE_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_directory ${CMAKE_SOURCE_DIR}/examples
            $<TARGET_FILE_DIR:${PROJECT_NAME}>/examples)
endif()

if(EXISTS ${CMAKE_SOURCE_DIR}/json_database)
  add_custom_command(
    TARGET setup-examples
    PRE_BUILD
    COMMAND
      ${CMAKE_COMMAND} -E copy_directory ${CMAKE_SOURCE_DIR}/json_database
      $<TARGET_FILE_DIR:${PROJECT_NAME}>/json_database)
endif()

if(EXISTS ${CMAKE_SOURCE_DIR}/tests)
  add_custom_command(
    TARGET setup-test
    PRE_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_directory ${CMAKE_SOURCE_DIR}/tests
            $<TARGET_FILE_DIR:${PROJECT_NAME}>/tests)
endif()

if(HERMES_TESTS)
  enable_testing()

  if (BOUT_ENABLE_METRIC_3D)
    find_program(PYTHON_EXECUTABLE
      NAMES python3.12 python3
      REQUIRED
    )
    
    add_custom_command(TARGET setup-test PRE_BUILD
      COMMAND ${PYTHON_EXECUTABLE} create_fci_grids.py
      WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/grids
    )
    file(CREATE_LINK ${CMAKE_CURRENT_SOURCE_DIR}/grids ${CMAKE_CURRENT_BINARY_DIR}/grids SYMBOLIC)
  endif()
  
  # Integrated tests
  function(hermes_add_integrated_test TESTNAME)
    set(oneValueArgs DOWNLOAD DOWNLOAD_NAME)
    set(multiValueArgs REQUIRES CONFLICTS)
    cmake_parse_arguments(HERMES_TEST_OPTIONS "${options}" "${oneValueArgs}"
                          "${multiValueArgs}" ${ARGN})

    foreach(REQUIREMENT IN LISTS HERMES_TEST_OPTIONS_REQUIRES)
      if(NOT ${REQUIREMENT})
        message(
          STATUS
            "Not building test ${TESTNAME}, requirement not met: ${REQUIREMENT}"
        )
        return()
      endif()
    endforeach()

    foreach(CONFLICT IN LISTS HERMES_TEST_OPTIONS_CONFLICTS)
      if(${CONFLICT})
        message(
          STATUS "Not building test ${TESTNAME}, conflicts with: ${CONFLICT}")
        return()
      endif()
      message(STATUS "CONFLICT ${CONFLICT} ${${CONFLICT}}")
    endforeach()

    if(HERMES_COPY_TESTS_TO_BUILD)
      set(INT_TEST_SRC ${CMAKE_CURRENT_SOURCE_DIR}/tests/integrated/${TESTNAME})
      set(INT_TEST_DEST
          ${CMAKE_CURRENT_BINARY_DIR}/tests/integrated/${TESTNAME})
      # Make copies of the test exec and input file in the build directory and
      # keep them up to date
      configure_file(${INT_TEST_SRC}/runtest ${INT_TEST_DEST}/runtest COPYONLY)
      configure_file(${INT_TEST_SRC}/data/BOUT.inp
                     ${INT_TEST_DEST}/data/BOUT.inp COPYONLY)
    else()
      set(INT_TEST_DEST
          ${CMAKE_CURRENT_SOURCE_DIR}/tests/integrated/${TESTNAME})
    endif()
    add_test(
      NAME ${TESTNAME}
      WORKING_DIRECTORY ${INT_TEST_DEST}
      COMMAND runtest)
    set_tests_properties(${TESTNAME} PROPERTIES LABELS integration)

    if(HERMES_TEST_OPTIONS_DOWNLOAD)
      if(NOT HERMES_TEST_OPTIONS_DOWNLOAD_NAME)
        message(FATAL_ERROR "We need DOWNLOAD_NAME if we should DOWNLOAD!")
      endif()
      file(REAL_PATH ${HERMES_TEST_OPTIONS_DOWNLOAD_NAME} DOWNLOAD_DEST_PATH
           BASE_DIRECTORY ${INT_TEST_DEST})
      add_custom_command(
        OUTPUT ${HERMES_TEST_OPTIONS_DOWNLOAD_NAME}
        COMMAND wget -nv ${HERMES_TEST_OPTIONS_DOWNLOAD} -O
                ${HERMES_TEST_OPTIONS_DOWNLOAD_NAME}
        WORKING_DIRECTORY ${INT_TEST_DEST}
        COMMENT "Downloading test data to ${DOWNLOAD_DEST_PATH}")
      # Custom target to run download command; use sanitised absolute path for
      # the target name
      string(REPLACE "/" "_" DOWNLOAD_TARGET_NAME ${DOWNLOAD_DEST_PATH})
      add_custom_target(
        ${DOWNLOAD_TARGET_NAME} ALL
        DEPENDS ${HERMES_TEST_OPTIONS_DOWNLOAD_NAME}
        DEPENDS setup-test)
    endif()
  endfunction()

  hermes_add_integrated_test(1D-fluid)
  hermes_add_integrated_test(1D-recycling)
  hermes_add_integrated_test(1D-recycling-dthe)
  hermes_add_integrated_test(diffusion)
  hermes_add_integrated_test(evolve_density)
  hermes_add_integrated_test(neutral_mixed)
  hermes_add_integrated_test(vorticity)
  hermes_add_integrated_test(sod-shock)
  hermes_add_integrated_test(sod-shock-energy)
  hermes_add_integrated_test(drift-wave)
  hermes_add_integrated_test(alfven-wave)
  hermes_add_integrated_test(collfreq-braginskii-afn)
  hermes_add_integrated_test(collfreq-multispecies)
  hermes_add_integrated_test(2D-production)
  hermes_add_integrated_test(2D-energy)
  hermes_add_integrated_test(2D-recycling)

  # Fci tests
  function(hermes_add_fci_test TESTNAME)
    set(oneValueArgs DOWNLOAD DOWNLOAD_NAME)
    set(multiValueArgs REQUIRES CONFLICTS)
    cmake_parse_arguments(HERMES_TEST_OPTIONS "${options}" "${oneValueArgs}"
                          "${multiValueArgs}" ${ARGN})

    foreach(REQUIREMENT IN LISTS HERMES_TEST_OPTIONS_REQUIRES)
      if(NOT ${REQUIREMENT})
        message(
          STATUS
            "Not building fci test ${TESTNAME}, requirement not met: ${REQUIREMENT}"
        )
        return()
      endif()
    endforeach()

    foreach(CONFLICT IN LISTS HERMES_TEST_OPTIONS_CONFLICTS)
      if(${CONFLICT})
        message(
          STATUS "Not building fci test ${TESTNAME}, conflicts with: ${CONFLICT}")
        return()
      endif()
      message(STATUS "CONFLICT ${CONFLICT} ${${CONFLICT}}")
    endforeach()

    if(HERMES_COPY_TESTS_TO_BUILD)
      set(FCI_TEST_SRC ${CMAKE_CURRENT_SOURCE_DIR}/tests/fci/${TESTNAME})
      set(FCI_TEST_DEST
          ${CMAKE_CURRENT_BINARY_DIR}/tests/fci/${TESTNAME})
      # Make copies of the test exec and input file in the build directory and
      # keep them up to date
      configure_file(${FCI_TEST_SRC}/runtest ${FCI_TEST_DEST}/runtest COPYONLY)
      configure_file(${FCI_TEST_SRC}/data/BOUT.inp
                     ${FCI_TEST_DEST}/data/BOUT.inp COPYONLY)
    else()
      set(FCI_TEST_DEST
          ${CMAKE_CURRENT_SOURCE_DIR}/tests/fci/${TESTNAME})
    endif()
    add_test(
      NAME ${TESTNAME}
      WORKING_DIRECTORY ${FCI_TEST_DEST}
      COMMAND runtest)
    set_tests_properties(${TESTNAME} PROPERTIES LABELS fci)

    if(HERMES_TEST_OPTIONS_DOWNLOAD)
      if(NOT HERMES_TEST_OPTIONS_DOWNLOAD_NAME)
        message(FATAL_ERROR "We need DOWNLOAD_NAME if we should DOWNLOAD!")
      endif()
      file(REAL_PATH ${HERMES_TEST_OPTIONS_DOWNLOAD_NAME} DOWNLOAD_DEST_PATH
           BASE_DIRECTORY ${FCI_TEST_DEST})
      add_custom_command(
        OUTPUT ${HERMES_TEST_OPTIONS_DOWNLOAD_NAME}
        COMMAND wget -nv ${HERMES_TEST_OPTIONS_DOWNLOAD} -O
                ${HERMES_TEST_OPTIONS_DOWNLOAD_NAME}
        WORKING_DIRECTORY ${FCI_TEST_DEST}
        COMMENT "Downloading test data to ${DOWNLOAD_DEST_PATH}")
      # Custom target to run download command; use sanitised absolute path for
      # the target name
      string(REPLACE "/" "_" DOWNLOAD_TARGET_NAME ${DOWNLOAD_DEST_PATH})
      add_custom_target(
        ${DOWNLOAD_TARGET_NAME} ALL
        DEPENDS ${HERMES_TEST_OPTIONS_DOWNLOAD_NAME}
        DEPENDS setup-test)
    endif()
  endfunction()
  
  hermes_add_fci_test(1D-density-fci)
  hermes_add_fci_test(1D-momentum-fci)
  hermes_add_fci_test(1D-pressure-fci)
  hermes_add_fci_test(1D-conduction-fci)

  hermes_add_fci_test(1D-ionviscosity-fci)
  hermes_add_fci_test(1D-electronviscosity-fci)
  hermes_add_fci_test(1D-sheath-goldenanswer-fci)

  hermes_add_fci_test(2D-density-anomalous-fci)

  # Unit tests
  option(HERMES_UNIT_TESTS "Build the unit tests" ON)
  if(HERMES_UNIT_TESTS)
    if(NOT PACKAGE_TESTS)
      # Not running BOUT++ tests Since BOUT++ includes googletest, adding it
      # again causes errors
      add_subdirectory(external/googletest)
    endif()
    file(GLOB_RECURSE TEST_SOURCES tests/unit/test_*.cxx)

    add_executable(hermes_unit_tests tests/unit/main.cxx ${TEST_SOURCES})

    target_link_libraries(hermes_unit_tests PRIVATE hermes_warnings)

    add_test(NAME hermes_unit_tests COMMAND hermes_unit_tests)
    set_tests_properties(hermes_unit_tests PROPERTIES LABELS unit)
    target_link_libraries(hermes_unit_tests PRIVATE gtest bout++::bout++
                                                    hermes-3-lib)
    # Have hermes_unit_tests look for dynamic libs in ./ before searching
    # elsewhere
    set_target_properties(hermes_unit_tests PROPERTIES BUILD_RPATH "$ORIGIN")
  endif()

  # Method of manufactured solutions (MMS) tests of operators
  option(HERMES_DIVOPS_MMS_TESTS "Build the differential operator MMS tests" ON)
  if(HERMES_DIVOPS_MMS_TESTS)
    # TEST_SOURCES=
    add_executable(hermes_mms_operator_tests tests/mms_operator/main.cxx)
    # ${TEST_SOURCES})
    target_link_libraries(hermes_mms_operator_tests
                          PRIVATE gtest bout++::bout++ hermes-3-lib)
    add_test(
      NAME differential_operators_mms_orthogonal
      WORKING_DIRECTORY tests/mms_operator/
      COMMAND python3 orthogonal_test.py)
    set_tests_properties(differential_operators_mms_orthogonal
                         PROPERTIES LABELS integration)
    add_test(
      NAME differential_operators_mms_nonorthogonal
      WORKING_DIRECTORY tests/mms_operator/
      COMMAND python3 nonorthogonal_test.py)
    set_tests_properties(differential_operators_mms_nonorthogonal
                         PROPERTIES LABELS integration)
    add_test(
      NAME rhs_mms_neutral_mixed
      WORKING_DIRECTORY tests/mms_operator/
      COMMAND python3 neutral_mixed_ddt_test.py)
    set_tests_properties(rhs_mms_neutral_mixed PROPERTIES LABELS integration)
  endif()
endif()

# Compile-time options

set(SLOPE_LIMITERS MC VanAlbada WENO3 MinMod Upwind Superbee)
set(HERMES_SLOPE_LIMITER
    MC
    CACHE STRING "Set advection slope limiter")
set_property(CACHE HERMES_SLOPE_LIMITER PROPERTY STRINGS ${SLOPE_LIMITERS})
message(STATUS "Slope limiter: ${HERMES_SLOPE_LIMITER}")

set(CONDUCTION_METHODS Original ProductJK Harmonic)
set(HERMES_CONDUCTION_METHOD
    Original
    CACHE STRING "Parallel conduction method")
set_property(CACHE HERMES_CONDUCTION_METHOD PROPERTY STRINGS
                                                     ${CONDUCTION_METHODS})
message(STATUS "Conduction method: ${HERMES_CONDUCTION_METHOD}")

# Generate the build config header

if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/include/hermes_build_config.hxx")
  # If we do in source builds, this is fine
  if(NOT ${CMAKE_CURRENT_SOURCE_DIR} STREQUAL ${CMAKE_CURRENT_BINARY_DIR})
    message(
      FATAL_ERROR
        "Generated hermes_build_config.hxx header already exists; please remove '${CMAKE_CURRENT_SOURCE_DIR}/include/hermes_build_config.hxx' before continuing"
    )
  endif()
endif()

configure_file(include/hermes_build_config.hxx.in
               include/hermes_build_config.hxx)

# Installation
if(BUILD_SHARED_LIBS)
  install(TARGETS hermes-3 hermes-3-lib)
else()
  install(TARGETS hermes-3)
endif()
